name: ci

on:
  push:
  workflow_call:

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          version: 2026.1.1
          install: true
          experimental: true
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.6"
      - name: Install dependencies
        run: go mod tidy
      - name: Run generate
        run: mise run generate
      - name: Run format
        run: mise run fmt
      - name: Check diff
        run: if [[ -n $(git diff --exit-code --name-only) ]]; then git diff --exit-code --name-only && exit 1; fi

  lint:
    needs: [prepare]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          version: 2026.1.1
          install: false
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.6"
      - name: Run lint
        run: mise run lint

  test:
    needs: [prepare]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          version: 2026.1.1
          install: false
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.6"
      - name: Run test
        run: mise run test

  build:
    needs: [prepare]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          version: 2026.1.1
          install: false
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.6"
      - name: Run build
        run: mise run build
